---
 - name: Create a login user
     user:
      name: "{{ username }}"
      password: "{{ password }}"
      groups: # Empty by default, here we give it some groups
       - sudo
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/fideloper  # Defaults to /home/<username>
